import type { TouristSpot } from "@/types/spot";
import { SpotCard } from "@/components/spot-card";

interface SpotGridProps {
  spots: TouristSpot[];
  locationName: string;
}

export function SpotGrid({ spots, locationName }: SpotGridProps) {
  return (
    <section>
      {/* Section header */}
      <div className="flex items-baseline justify-between mb-6 pb-4 border-b border-border">
        <div>
          <h2
            className="font-bold text-warm-text text-2xl"
            style={{ fontFamily: "var(--font-lora)" }}
          >
            {spots.length} Spots Discovered
          </h2>
          <p className="text-warm-muted text-sm mt-0.5">in {locationName}</p>
        </div>

        {/* Legend */}
        <div className="hidden sm:flex items-center gap-1.5 text-xs text-warm-muted">
          <span className="text-amber-400">★</span>
          <span>AI-curated picks</span>
        </div>
      </div>

      {/* Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {spots.map((spot) => (
          <SpotCard key={spot.id} spot={spot} />
        ))}
      </div>

      {/* Footer note */}
      <p className="text-center text-warm-muted text-xs mt-10 opacity-60">
        All spots are generated by AI and may need verification before visiting.
      </p>
    </section>
  );
}
